### ISSUE TITLE
[BUG] Syntax Error in SASS

### ISSUE THREAD

**Issue by greenfrogs** [uclapi/uclapi#3453]
**Describe the bug**
Syntax error inside `uclapi.scss`, additional comma after button

```css
.emphasis-button, {
  background-color: lighten($primary-highlight-color, 10%);
  color: black;
}
```
